### ISSUE TITLE
New 1.0 roadmap

### ISSUE THREAD

**Issue by CrowdHailer** [CrowdHailer/raxx#167]
This is the follow up to #118, it was decided at least one more breaking release should be done before 1.0

### Checklist

- [x] remove code with warnings e.g. old router format
- [x] ~~EExHTML 1.0 release, make it have an optional dependency on  Jason.
  This is because I think EExHTML might remain a dependency of the core raxx to the page that it puts as default callbacks
  redirect function relies on this.~~
- [x] Rather than configuring the extra status codes
`Raxx.response({422, "Unprocessable Entity"})`
Add a new field to response struct, that is optional. Ace will have to send "Unknown" if it is not set. or nothing in HTTP/2 land which is fine
- [x]  Reinstate/Remove skipped tests
- [x]  Fix travis for OTP 21.3

## Optional Checklist
- [x] ~~Drop the `raw_path` field on a request
  Have only path and that should contain the raw binary. Then introduce `Raxx.segments(request)` to return the split path~~

**Comment by CrowdHailer** [comment]
Thanks to @lasseebert and his work to remove `EExHTML` as a dependency (#171) we can drop a `1.0` for EExHTML as a requirement for Raxx 1.0

**Comment by CrowdHailer** [comment]
I think we are ready for a 1.0 release :tada: 

My opinions on all that remains is.

1. Don't do anything relating to being able to choose the reason phrase in a response. It can be added as a non breaking change after 1.0
2. remove the [final skipped test](https://github.com/CrowdHailer/raxx/blob/next/test/raxx/router_test.exs#L211-L218) the router should not make assumptions about what metadata to add as it is intended as a base layer on top of which more sophisticated routing can be built
3. Leave `raw_path` as it is now.

**Comment by CrowdHailer** [comment]
Thanks for the comments.

I don't think we can remove `extra_statuses` without implementing the replacement. We use it and it hasn't caused any problems for us. but that's all I have. I don't think it's the best solution I'm just also not sure it's worth stopping 1.0 for it??

**Comment by nietaki** [comment]
What I meant with extra statuses is that we could allow for arbitrary `{status_code_integer(), status_name_string}` tuple in the `%Raxx.Response{}` status field (and any functions that take the status as an atom or integer).

This way the user could still send arbitrary statuses, but without the need for a global config. It wouldn't be difficult to use either, in your user code you could just define `def unprocessable_entity(), do: {422, "Unprocessable Entity"}` and use it wherever needed.

I think this would be a clean solution, requiring minimal code changes and making Raxx independent of Mix.Config. Plus I think that the assumption that everything in the user app would like to share the extra statuses might not always be correct.

**Comment by CrowdHailer** [comment]
I like the proposal. 
But does it need to be a thing before 1.0?
`Raxx.request()` currently takes `atom | integer` after it would take `atom | integer | {integer, binary`
That could be added at 1.1?

**Comment by nietaki** [comment]
My reply from 2 days ago didn't send :/

There's a couple of reasons why I'd like to get that in before 1.0:
- it is an API-breaking change and I think we'd like the API to be a bit more stable after 1.0. For how small of a change this is, I'd understand the resistance against doing it post 1.0
- It's the only place where Raxx depends on Mix.Config and I don't think we're getting a bang for our buck. I think making Raxx independent of the config would make it cleaner / more functional
- With the way it is right now, there's an in-built assumption that all the code sharing the config will use the same extra statuses. This might not always be true

**Comment by CrowdHailer** [comment]
Alright I'm sold.
I do think that when this gets implemented it should go as a `0.19.x` release. And exists for a bit in the wild. I will at least get feedback from using it in my own projects

**Comment by CrowdHailer** [comment]
It is worth noting that HTTP/2 does have reason phrases and HTTP/1.1 can have responses with no reason phrase and you can already pass any integer to `Raxx.response`

So any status code is already supported by just passing an integer when making the response.
I wonder what plug/phoenix/cowboy does

**Comment by CrowdHailer** [comment]
Going on the points above I have added this test. 
https://github.com/CrowdHailer/raxx/pull/172/commits/f01963748f52796b063c441a3de9f3b97d9b6a5c

In my opinion that shows that we can handle any status code. 
if you want words then define a function that returns an integer and use as follows
```elixir
def my_status(), do: 299

Raxx.response(my_status()
```

I don't think there is any need to support custom status wording.

**Comment by CrowdHailer** [comment]
Here's the commit on the next branch https://github.com/CrowdHailer/raxx/pull/172/commits/dd2ee03e54e785d5dac31bce98e7a0b7e45bd8a6
