### ISSUE TITLE
Raxx.View 1.0 Roadmap

### ISSUE THREAD

**Issue by CrowdHailer** [CrowdHailer/raxx#178]
Requirements to get Raxx.View to 1.0

### Required

- [x] EExHTML 1.0 released https://hex.pm/packages/eex_html
- [ ] Correct line numbers for stacktraces in templates. #132 (needs some specific tests of stacktraces, or otherwise return file line info)

### Questions

- [ ] is `__content__` a helpful special word in layouts.
- [ ] Do we need some pattern for optional variables?
